version: '3.7'

x-config: &config
  build:
    context: .
    dockerfile: thanks.dockerfile


services:
  local:
    <<: *config
    environment:
      HOSTNAME: "0.0.0.0"
      PORT: 8080
    ports:
      - "8080:8080"
  prod:
    <<: *config
    environment:
      HOSTNAME: "thanksasaservice.com"
      PORT: 80
    ports:
      - "80:80"
